services:
  # Memcached
  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    ports:
      - "11211:11211"
    command: memcached -m 64 -p 11211 -u nobody

  # Redis Single Instance
  redis-single:
    image: redis:7-alpine
    container_name: redis-single
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_single_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-cluster-1:
    image: redis:7-alpine
    container_name: redis-cluster-1
    ports:
      - "7000:7000"
    command: >
      redis-server
      --port 7000
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip redis-cluster-1
      --cluster-announce-port 7000
    volumes:
      - redis_cluster_1_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7000", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-cluster-2:
    image: redis:7-alpine
    container_name: redis-cluster-2
    ports:
      - "7001:7001"
    command: >
      redis-server
      --port 7001
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip redis-cluster-2
      --cluster-announce-port 7001
    volumes:
      - redis_cluster_2_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7001", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-cluster-3:
    image: redis:7-alpine
    container_name: redis-cluster-3
    ports:
      - "7002:7002"
    command: >
      redis-server
      --port 7002
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip redis-cluster-3
      --cluster-announce-port 7002
    volumes:
      - redis_cluster_3_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7002", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    depends_on:
      redis-cluster-1:
        condition: service_healthy
      redis-cluster-2:
        condition: service_healthy
      redis-cluster-3:
        condition: service_healthy
    command:
      - sh
      - -c
      - |
        echo 'Waiting for cluster nodes…' &&
        sleep 20 &&
        echo 'Creating Redis cluster…' &&
        redis-cli --cluster create \
          redis-cluster-1:7000 \
          redis-cluster-2:7001 \
          redis-cluster-3:7002 \
          --cluster-replicas 0 --cluster-yes &&
        echo 'Redis cluster ready!'
    restart: "no"

volumes:
  redis_single_data:
  redis_cluster_1_data:
  redis_cluster_2_data:
  redis_cluster_3_data:
